# Generated by Django 2.2.9 on 2020-01-11 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url_height',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AddField(
            model_name='photo',
            name='url_width',
            field=models.PositiveIntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='photo',
            name='pic',
            field=models.ImageField(height_field='url_height', upload_to='booktest', width_field='url_width'),
        ),
    ]
