# Generated by Django 2.2.9 on 2020-01-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20200106_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photopage',
            name='image',
        ),
    ]
