# Generated by Django 2.2.9 on 2020-01-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20200111_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='url_height',
            new_name='pic_height',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='url_width',
            new_name='pic_width',
        ),
        migrations.AlterField(
            model_name='photo',
            name='pic',
            field=models.ImageField(height_field='pic_height', upload_to='booktest', width_field='pic_width'),
        ),
    ]
