# Generated by Django 2.2.9 on 2020-02-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_auto_20200126_2052'),
        ('photo', '0005_auto_20200111_2215'),
    ]

    operations = [
    ]
